### ISSUE TITLE
Fone

### ISSUE THREAD

**Issue by samueljrz** [salmomascarenhas/Agenda#1]
public class Fone {

	String idFone;
	static String number;
	
public Fone (String idFone, String number)	{
	this.idFone = idFone;
	Fone.number = number;
	}

public boolean validacao (String number)	{
	 if (number.length() == 9) {
		 return true; 
	 }
	 //else if ()	{
		 	
//	 }
	return false;
	}
	
	public static void main(String args[]) {
		Fone salmo = new Fone("sadsd", "1234567892");
		if (salmo.validacao(number)) {
			System.out.println("ok");
		}
		else
			System.out.println("nao ok");

	}
	
}

**Comment by samueljrz** [comment]
public class Contato {
	
	public String idContato;
	public Fone Telefones;
	public boolean Favorito;
	
	public Contato (String idContato, Fone Telefones, boolean Favorito)	{
		this.idContato = idContato;
		this.Telefones = Telefones;
		this.Favorito = Favorito;
	}
	
	public boolean addFone (Fone Telefones) {
		
	}
	
	public boolean rmFone (DDD String)	{
		
	}
	
	
}

**Comment by salmomascarenhas** [comment]
class Fone {
	//atributos
	String idFone;
	String number;
	
	public Fone () {
		this.idFone = "00";
		this.number = "000000000";
	}
	

	void validacao (String number)	{
	if (number.length() == 9) {
		System.out.println("Deu certo");
		}
}


}


public class Program {
	public static void main (String[] args) {
		Fone c = new Fone();
		
		c.validacao("123456789");
		
	}

}

**Comment by samueljrz** [comment]
import java.util.ArrayList;

public class Pet {
    
    static int qtd = 0;
	String nome;
	String raca;
	int idade; 
	boolean isAlive;
	int vidas;
	
	
	public Pet(String nome, String raca, int idade){
		this.nome = nome;
		this.raca = raca;
		this.idade = idade;
		this.isAlive = true;
		this.vidas = 1;
		if (this.raca.equals("Cat"))
			this.vidas = 7; 
		Pet.qtd += 1;
	}
	
	public void fazer_barulho(){
		if (this.isAlive){
			if (this.raca.equals("Dog"))
				System.out.println ("au au");
			else if (this.raca.equals("Cat"))
				System.out.println ("miau");
			else
				System.out.println ("iiiiiiiiii");
		} else
			System.out.println("RIP");
	}

	public void falar_nome()	{
		if(this.isAlive) {
			if(this.raca.equals("cat")) 
				System.out.println ("my name is:"	+	this.nome);
			
			else if(this.raca.equals("dog"))	
			 	System.out.println ("my name is:"	+	this.nome);
			
			else	
				System.out.println ("my name is:"	+	this.nome);
			
		} 
		else
			System.out.println("Iam DEAD!");
		
	}
	
	
	public String toString(){
		String result = "Animal " + this.nome + " " + this.raca;
		result += " " + this.idade + " Vivo: " + this.isAlive;
		return result;
	}

	public void atravessar_a_rua(){
		if (this.isAlive){
			this.vidas -= 1;
			if (this.vidas == 0)
				this.isAlive = false;
		}
	}
	
    public static void main(String args[]) {
        
        ArrayList<Pet> zoo = new ArrayList<Pet>();
        zoo.add(new Pet("Dog", "Dog", 5));
        zoo.add(new Pet("Xaninha", "Cat", 7));
        zoo.add(new Pet("Giba", "Soin", 2));
	
        boolean tem_vivo = true;	
        while(tem_vivo){
        	tem_vivo = false;
        	for (Pet animal : zoo){
        		animal.fazer_barulho();
        		animal.falar_nome();
        		animal.atravessar_a_rua();
        		if(animal.isAlive)
        			tem_vivo = true;
        		System.out.println(animal);
        	}
        }
    }
}

**Comment by 0402749** [comment]
package Fone; 

public class Fone  {

		String idFone;
		static String number;
		static int ctnum;


public Fone (String idFone, String number, int ctnum)	
	{

		this.idFone = idFone;
		Fone.number = number;
		Fone.ctnum = 0;
	}

public boolean validacao (String number)	
	{
		if (number.length() == 9) 
		{				
			System.out.println("tem 9 caracteres");
	
			for (int i = 0; i <= 8; i++) 
			{
				if ((number.charAt(i) >= '0') && (number.charAt(i) <= '9')) 
				{
				ctnum += 1;
				}
			}
				if (ctnum == 9)
				{
				System.out.println("sao todos numeros");
					return true;
				}
				else
				System.out.println("não é válido pq tem letra");
				return false;		
		}				
				System.out.println("invalido");
				return false;
	}



public static void main(String args[]) {
	Fone salmo = new Fone("sadsd", "123456789", ctnum);
	salmo.validacao(number);
	}
}

**Comment by salmomascarenhas** [comment]
import java.util.ArrayList;

class Contato{
	String idContato;
	ArrayList<Fone> fones = new ArrayList<Fone>();
	boolean favorited;
	
}
